/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_MyClass */

#ifndef _Included_application_MyClass
#define _Included_application_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_MyClass
 * Method:    getSchedule
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_application_MyClass_getSchedule
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
